// Autogenerated from Pigeon (v1.0.12), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, ProviderMode) {
  ProviderModeLive = 0,
  ProviderModeTest = 1,
};

typedef NS_ENUM(NSUInteger, TransactionType) {
  TransactionTypeSync = 0,
  TransactionTypeAsync = 1,
};

typedef NS_ENUM(NSUInteger, YooKassaStatus) {
  YooKassaStatusSucceeded = 0,
  YooKassaStatusPending = 1,
  YooKassaStatusWaitingForCapture = 2,
  YooKassaStatusCanceled = 3,
  YooKassaStatusUndefined = 4,
};

typedef NS_ENUM(NSUInteger, STCPayVerificationOption) {
  STCPayVerificationOptionMobilePhone = 0,
  STCPayVerificationOptionQrCode = 1,
};

typedef NS_ENUM(NSUInteger, AuthStatus) {
  AuthStatusAuthenticated = 0,
  AuthStatusAttemptProcessingPerformed = 1,
  AuthStatusChallengeRequired = 2,
  AuthStatusDecoupledConfirmed = 3,
  AuthStatusDenied = 4,
  AuthStatusRejected = 5,
  AuthStatusFailed = 6,
  AuthStatusInformationalOnly = 7,
};

@class Transaction;
@class ThreeDS2Info;
@class PaymentParams;
@class YooKassaInfo;
@class FlutterOppwaException;
@class PaymentError;
@class CardTransaction;

@interface Transaction : NSObject
@property(nonatomic, strong, nullable) PaymentParams * paymentParams;
@property(nonatomic, assign) TransactionType transactionType;
@property(nonatomic, copy, nullable) NSString * redirectUrl;
@property(nonatomic, copy, nullable) NSString * threeDS2MethodRedirectUrl;
@property(nonatomic, strong, nullable) ThreeDS2Info * threeDS2Info;
@property(nonatomic, strong, nullable) YooKassaInfo * yooKassaInfo;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * brandSpecificInfo;
@end

@interface ThreeDS2Info : NSObject
@property(nonatomic, assign) AuthStatus authStatus;
@property(nonatomic, copy, nullable) NSString * authResponse;
@end

@interface PaymentParams : NSObject
@property(nonatomic, copy, nullable) NSString * checkoutId;
@property(nonatomic, copy, nullable) NSString * paymentBrand;
@property(nonatomic, copy, nullable) NSString * shopperResultUrl;
@end

@interface YooKassaInfo : NSObject
@property(nonatomic, assign) YooKassaStatus status;
@property(nonatomic, copy, nullable) NSString * confirmationUrl;
@property(nonatomic, copy, nullable) NSString * callbackUrl;
@end

@interface FlutterOppwaException : NSObject
@property(nonatomic, copy, nullable) NSString * errorCode;
@property(nonatomic, copy, nullable) NSString * errorMessage;
@property(nonatomic, strong, nullable) PaymentError * paymentError;
@end

@interface PaymentError : NSObject
@property(nonatomic, copy, nullable) NSString * code;
@property(nonatomic, copy, nullable) NSString * message;
@property(nonatomic, copy, nullable) NSString * info;
@property(nonatomic, strong, nullable) Transaction * transaction;
@end

@interface CardTransaction : NSObject
@property(nonatomic, copy, nullable) NSString * checkoutId;
@property(nonatomic, copy, nullable) NSString * number;
@property(nonatomic, copy, nullable) NSString * brand;
@property(nonatomic, copy, nullable) NSString * holder;
@property(nonatomic, copy, nullable) NSString * expiryMonth;
@property(nonatomic, copy, nullable) NSString * expiryYear;
@property(nonatomic, copy, nullable) NSString * cvv;
@end

/// The codec used by OppwaApi.
NSObject<FlutterMessageCodec> *OppwaApiGetCodec(void);

@protocol OppwaApi
- (void)initializeMode:(NSNumber *)mode error:(FlutterError *_Nullable *_Nonnull)error;
- (void)submitCardTransactionTransaction:(nullable CardTransaction *)transaction completion:(void(^)(FlutterError *_Nullable))completion;
- (void)errorWithCompletion:(void(^)(FlutterOppwaException *_Nullable, FlutterError *_Nullable))completion;
@end

extern void OppwaApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<OppwaApi> *_Nullable api);

NS_ASSUME_NONNULL_END
